### ISSUE TITLE
StatsWriterPlugin not working when running through mocha-webpack

### ISSUE THREAD

**Issue by lewisf** [zinserjan/mocha-webpack#107]
For context, I'm attempting to retrofit mocha-webpack onto a pretty big javascript application that we have. I'm trying to debug why the webpack compilation phase of running tests with mocha-webpack is very slow on a pretty big application I'm working on.

I've added the StatsWriterPlugin to my webpack test configuration, but it doesn't look like it's outputting stats.json files.

```
plugins: [
   new StatsWriterPlugin({
     filename: "stats.json"
   })
]
```

When I use the config with `webpack --config webpack.config.test.js` it generates the stats.json fine.

Reproducible on the `mocha-webpack-example` by just adding the StatsWriterPlugin as documented here:
https://github.com/FormidableLabs/webpack-stats-plugin#basic

Here's [a comparison to my fork of the `mocha-webpack-example` repo](https://github.com/zinserjan/mocha-webpack-example/compare/master...lewisf:lewis/test-stats-plugin?expand=1) with the minimal changes to reproduce:

**Comment by zinserjan** [comment]
The problem is that mocha-webpack compiles everything into a [memory-fs](https://github.com/webpack/memory-fs). 

StatsWriterPlugin let webpack emit the files (see https://github.com/FormidableLabs/webpack-stats-plugin/blob/3c7fc56f5b3cac8967b1fd275bea8a994b5bce96/lib/stats-writer-plugin.js#L78). And that's the problem as it writes to memory.

You need a plugin which doesn't write to memory. Something like this should work (untested):

```javascript
{
  plugins:
  [
    {
      apply: compiler => {
        compile.plugin("done", stats => {
          // see https://github.com/webpack/webpack/blob/master/bin/webpack.js#L179
          // same like webpack --json > stats.json
          const outputOptions = require("webpack/lib/Stats").presetToOptions();
          const statsJSON = stats.toJson(outputOptions);
          // see https://github.com/webpack/webpack/blob/master/bin/webpack.js#L336
          require("fs").writeFileSync("stats.json", JSON.stringify(stats.toJson(outputOptions), null, 2));
        });
      }
    }
  ];
}

```
