### ISSUE TITLE
not work with webpack config file written in es6 syntax

### ISSUE THREAD

**Issue by craigcosmo** [zinserjan/mocha-webpack#51]
I made a demo in which the webpack config is written in es6 syntax. When I run the command, I got   error `Unexpected token import`

The demo hosted at: https://github.com/craigcosmo/react-redux-test

**Comment by zinserjan** [comment]
There are no instructions or usages of mocha-webpack there.

**Comment by craigcosmo** [comment]
I updated the readme. Also the command in package.json.

**Comment by ezze** [comment]
It's possible to use Babel in your webpack config file if you add `--require babel-core/register` to command line or `mocha-webpack.opts` file.

Unfortunately, it's not working with Babel 6. The reason is that Babel 6 doesn't assign `export default` to `module.exports` as it was with Babel 5. See [this StackOverflow question](http://stackoverflow.com/q/33704714/506695) for more details.

#53 allows to use ES6 syntax in wepback config, just give it a name ending with `.babel.js`:

    import nodeExternals from 'webpack-node-externals';

    export default {
      target: 'node', // in order to ignore built-in modules like path, fs, etc.
      externals: [nodeExternals()], // in order to ignore all modules in node_modules folder    
    };

**Comment by zinserjan** [comment]
@ezze's PR is released as v0.7.0.

@craigcosmo give it a try :wink:
