### ISSUE TITLE
Too many non-option arguments: got 2, maximum of 1

### ISSUE THREAD

**Issue by dannybloe** [zinserjan/mocha-webpack#8]
Hi there, 

I've spent a couple of hours trying to get mocha-webpack to do anything but no matter what I throw at it, it keeps returning the error "Too many non-option arguments: got 2, maximum of 1". Even requesting the version number fails.

It seems as if it fails in receiving any command-line arguments. 

"mocha": "^2.4.5",
"mocha-webpack": "^0.3.0",
node: 5.7.0
"webpack": "^1.13.0"

Any help is greatly appreciated.

**Comment by zinserjan** [comment]
Sounds strange. Can you provide me the commands?

**Comment by bcowgill** [comment]
I got a similar error when I tried this in my package.json5 file 

        "mocha:watch": "mocha-webpack --webpack-config=config/webpack.config-test.js \
            --watch --colors \
            --require=source-map-support/register \
            --check-leaks --full-trace \
            test/es6/Browser.spec.js \
            test/es6/ErrorHandler.spec.js \
            src/templates/TemplateComponent.spec.js",

If I remove the last two test plans from the command line it works.
seems like you cannot specify more than one test plan

**Comment by zinserjan** [comment]
> seems like you cannot specify more than one test plan 

Yep, that's true. Multiple test entries are planned for 1.0.0.

> globs are causing other problems on our windows build machine

What's the issue with globs? Works fine for me on windows.

**Comment by bcowgill** [comment]
When I put --glob='src/**/*.spec.js' it appears to be including the ' into the path instead of stripping it.
when I leave off the quote then it gets the too many arguments error.

> mocha-webpack --webpack-config=config/webpack.config-test.js 			--colors --growl 			--require=source-map-support/register 			--check-leaks --full-trace 			'src/**/*.spec.js'

__dirname: d:\jenkins-slave\workspace\docuzilla-jaws-win\webui\config
srcDir: src
relSrcDir: ./src
fullSrcDir: d:\jenkins-slave\workspace\docuzilla-jaws-win\webui\src
fullTestDir: d:\jenkins-slave\workspace\docuzilla-jaws-win\webui\test

[1m[31mERROR in ./.tmp/mocha-webpack/fed01808532e87f8020e541a52ed62ef-entry.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../'src in d:\jenkins-slave\workspace\docuzilla-jaws-win\webui\.tmp\mocha-webpack
resolve file
resolve directory
  d:\jenkins-slave\workspace\docuzilla-jaws-win\webui\'src doesn't exist
 @ ./.tmp/mocha-webpack/fed01808532e87f8020e541a52ed62ef-entry.js 2:23-59[39m[22m

**Comment by texttechne** [comment]
@bcowgill don't use single quotes on windows. Use `\"` instead: An escaped double quote.

**Comment by supnate** [comment]
Thanks @texttechne ! Using \" resolves `Too many non-option arguments` error for me on Mac.

**Comment by zinserjan** [comment]
Closing this in favour of #45
